---
minio:
  address: s3system
  port: 9000   
  ssl: false
  bucket: gleaner
gleaner:
  runid: polder # Run ID used in prov and a few others
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "./schemaorg-current-https.jsonld"
- prefix: "http://schema.org/"
  file: "./schemaorg-current-https.jsonld"
- prefix: "http://schema.org/"
  file: "./schemaorg-current-https.jsonld"
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 5
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1) 
  headless: http://headless:9222  # URL for headless see docs/headless
millers:
  graph: true
sources:
- name: nsidc
  url: https://nsidc.org/sitemap.xml
  headless: false
  properName: National Snow and Ice Data Center
  domain: https://nsidc.org
  type: sitemap
  active: false
- name: gem
  type: sitemap
  headless: true
  url: https://data.g-e-m.dk/sitemap
  properName: Greenland Ecosystem Monitoring Database
  domain: https://data.g-e-m.dk
  active: false
- name: bas
  type: sitemap
  url: http://s3system:9000/sitemaps/bas-sitemap.xml
  properName: British Antarctic Survey
  active: true
  domain: http://bas.ac.uk
